In [1]:
import numpy as np

Bài 1


In [3]:
arr=np.ones((3,3),dtype=bool)
print("Mảng arr với các giá trị True: ")
print(arr)

Mảng arr với các giá trị True: 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Bài 2,3,4,5


In [5]:
arr_1D=np.array([0,1,2,3,4,5,6,7,8])
arr_2D=arr_1D.reshape(3,3)
arr_2D[:,[0,2]]=arr_2D[:,[2,0]]
print("Mảng sau khi đổi là:")
print(arr_2D)
###
arr_2D[[0,1]]=arr_2D[[1,0]]
print("Mảng sau khi đổi dòng là:")
print(arr_2D)
###
arr_2D_dao_nguoc=arr_2D[::-1]
print("Mảng 2D sau đảo ngược các dòng:")
print(arr_2D_dao_nguoc)
###
arr_2D_dao_nguoc_cot=arr_2D_dao_nguoc[:,::-1]
print("Mảng 2D sao khi đảo ngược các cột là:")
print(arr_2D_dao_nguoc_cot)



Mảng sau khi đổi là:
[[2 1 0]
 [5 4 3]
 [8 7 6]]
Mảng sau khi đổi dòng là:
[[5 4 3]
 [2 1 0]
 [8 7 6]]
Mảng 2D sau đảo ngược các dòng:
[[8 7 6]
 [2 1 0]
 [5 4 3]]
Mảng 2D sao khi đảo ngược các cột là:
[[6 7 8]
 [0 1 2]
 [3 4 5]]


Bài 6,7

In [6]:
arr_2D_null=np.array([[1,2,3],
                      [np.nan,5,6],
                      [7,np.nan,9],
                      [4,5,6]])
gia_tri_rong=np.any(np.isnan(arr_2D_null))
if gia_tri_rong:
    print("mảng có chứa giá trị NaN")
else:
    print("Mảng không có giá trị NaN")    
###
arr_2D_null[np.isnan(arr_2D_null)]=0
print("Mảng sau khi thay thế là:")
print(arr_2D_null)

mảng có chứa giá trị NaN
Mảng sau khi thay thế là:
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
